version: "3.3"
services:
  db:
    image: "postgres:13"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rx
      - POSTGRES_DB=todo
