version: "3.3"
services:
  db:
    image: "postgres:13"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rx
      - POSTGRES_DB=todo

  app:
    build: .
    ports:
      - "8080:8081"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=rx
      - DB_NAME=todo